src/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("/<str:name>",views.greet,name="greet"),
]

src/isitchristmas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    
]

src/practice/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include("hello.urls")),
    path("tasks/", include("tasks.urls")),
    path("isitchristmas/", include("isitchristmas.urls"))
]

src/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path('',views.index,name="index"),
    path('add/', views.add_task, name="add_task"),
]

src/tasks/models.py
from django.db import models

# Create your models here.

src/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Hello World")

# def greet(request,name):
#     return httpresponse(f"hello, {name.capitalize()}")


# def greet(request, name, template_name="hello/greet.html"):
#     #context = 
#     return render(request,  template_name, {
#         "name": name.capitalize()
#     })


def greet(request, name):
    #context =
    return render(request,  "hello/greet.html", {
        "name": name.capitalize()
    })

src/isitchristmas/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    
    return render(request, "isitchristmas/index.html",{
        'answer': now.month==12 and now.day==25
    })

src/tasks/views.py
from django.forms.fields import CharField
from django.http.response import HttpResponseRedirect
from django.shortcuts import  render
from django.urls import reverse
from django import forms


class NewTaskForm(forms.Form):
    task = forms.CharField(max_length=20, label="New Task",
                           widget=forms.TextInput(attrs={'placeholder': 'Task'}))


tasks = []

# Create your views here.


def index(request):
    ## to check if the tasks already exists in the session
    if "tasks" not in request.session:
        request.session["tasks"]=[]
    return render(request, "tasks/index.html", {
        'tasks': request.session["tasks"]
    })


def add_task(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            request.session["tasks"] += [task]
            # tasks.append(task)
            #### To reverse engineer URL
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            render(request, "tasks/add.html", {
                'form': form
            })

    return render(request, "tasks/add.html", {
        'form': NewTaskForm()
    })

src/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello, {{ name }}</h1>
</body>
</html>

src/isitchristmas/templates/isitchristmas/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link href="{% static 'isitchristmas/styles.css' %}" rel="stylesheet" />
    
  </head>
  <body>
    {% if answer %}
    <h1>Yes</h1>
    {% else %}
    <h1>No</h1>
    {% endif %}
  </body>
</html>

src/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Tasks</h1>
    <form action="{% url 'tasks:add_task' %}" method="POST">
        {% csrf_token %}
        <!-- <input type="text" name="task"> -->
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">Back &larr;</a>

{% endblock %}

src/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Tasks</h1>
    <ul>
    {% for item in tasks %}
    <li>{{ item }}</li>
    {% empty %}
        No Task
    {% endfor %}
    </ul>
    <a href="{% url 'tasks:add_task' %}">Add a new task</a>
{% endblock %}

src/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>